import { Translation } from './types';

export const TRANSLATIONS: Record<'bn' | 'en', Translation> = {
  en: {
    appTitle: 'Baki Hisab Manager',
    shops: 'My Shops',
    addShop: 'Add New Shop',
    shopName: 'Shop Name',
    shopType: 'Shop Type',
    shopTypePlaceholder: 'e.g. Tea Stall, Grocery',
    create: 'Create',
    update: 'Update',
    cancel: 'Cancel',
    dashboard: 'Home',
    settings: 'Settings',
    about: 'About',
    entries: 'Daily Entries',
    addEntry: 'Add Entry',
    date: 'Date',
    morning: 'Morning',
    noon: 'Noon',
    night: 'Night',
    total: 'Total',
    save: 'Save Entry',
    delete: 'Delete',
    edit: 'Edit',
    noShops: 'No shops found. Add one!',
    noEntries: 'No entries for this shop yet.',
    language: 'Language',
    bangla: 'Bangla',
    english: 'English',
    exportData: 'Export Backup (JSON)',
    importData: 'Import Backup',
    resetData: 'Reset All Data',
    confirmDelete: 'Are you sure?',
    totalDue: 'Total Due',
    monthlyTotal: 'This Month Total',
    version: 'Version',
    build: 'Build Number',
    createdBy: 'Created by Md Rasel',
    aboutDesc: 'A simple offline tool to manage your shop credits and daily expenses.',
    backupRestore: 'Backup & Restore',
    backupNote: 'Save your data to a file to keep it safe.',
  },
  bn: {
    appTitle: 'বাকি হিসাব ম্যানেজার',
    shops: 'আমার দোকানসমূহ',
    addShop: 'নতুন দোকান যোগ করুন',
    shopName: 'দোকানের নাম',
    shopType: 'দোকানের ধরন',
    shopTypePlaceholder: 'যেমন: চা দোকান, মুদি দোকান',
    create: 'তৈরি করুন',
    update: 'আপডেট করুন',
    cancel: 'বাতিল',
    dashboard: 'হোম',
    settings: 'সেটিংস',
    about: 'পরিচিতি',
    entries: 'দৈনিক হিসাব',
    addEntry: 'হিসাব যোগ করুন',
    date: 'তারিখ',
    morning: 'সকাল',
    noon: 'দুপুর',
    night: 'রাত',
    total: 'মোট',
    save: 'সংরক্ষণ করুন',
    delete: 'মুছুন',
    edit: 'এডিট',
    noShops: 'কোন দোকান নেই। নতুন যোগ করুন!',
    noEntries: 'এই দোকানের কোন হিসাব নেই।',
    language: 'ভাষা',
    bangla: 'বাংলা',
    english: 'English',
    exportData: 'ব্যাকআপ নিন (JSON)',
    importData: 'ব্যাকআপ রিস্টোর করুন',
    resetData: 'সব ডাটা মুছুন',
    confirmDelete: 'আপনি কি নিশ্চিত?',
    totalDue: 'সর্বমোট বাকি',
    monthlyTotal: 'এই মাসের মোট',
    version: 'ভার্সন',
    build: 'বিল্ড নম্বর',
    createdBy: 'তৈরি করেছেন: মোঃ রাসেল',
    aboutDesc: 'দোকানের বাকি এবং দৈনিক খরচের হিসাব রাখার একটি সহজ অফলাইন অ্যাপ।',
    backupRestore: 'ব্যাকআপ এবং রিস্টোর',
    backupNote: 'আপনার ডাটা নিরাপদ রাখতে ফাইলে সেভ করে রাখুন।',
  },
};